### ISSUE TITLE
Enhancement: Pull Data From Loop App

### ISSUE THREAD

**Issue by sooperlooper** [SpikeApp/Spike#151]
Hello!

I was wondering if Spike could pull data from the Loop app instead of Nightscout? 

I've noticed that some of the data displayed in Spike is often delayed since the flow uses Nightscout as a proxy and requires an internet connection.  The same data is available offline from the Loop app so I think pulling the data directly would really improve Spike for Loop users.

This is some of the data I'm referring to:

- Predictions
- Pump Battery
- Pump Reservoir
- COB
- IOB
- Minutes since last Loop
- Current Basal

Thank you so much for your consideration.

**Comment by miguelkennedy** [comment]
No... that data is not available for Spike to pull offline. Loop doesn't run an internal webserver like Spike nor does it provide an API to connect to.

Data from Loop should not be delayed by more than 15 seconds. Also, every time you open Spike or bring it to the foreground Spike automatically refreshes that data. If you press the predictions pill you'll also find a button to manually refresh that data if you so choose to. That's really the best I can do since there's no way to connect to Loop directly.

**Comment by sooperlooper** [comment]
![e397a7cd-b1b9-4c0e-9be4-684e044d5345](https://user-images.githubusercontent.com/36587731/50432916-fe8eb400-08a2-11e9-81b6-17d5ca6db957.jpeg)
![fb56cb1e-9cb6-476a-a78d-69bddf17e603](https://user-images.githubusercontent.com/36587731/50432917-ff274a80-08a2-11e9-95c0-7a585d1dac42.jpeg)

I see. Oh well, maybe that’s something Loop could support in the future. Right now I’m on vacation with intermittent wifi so that’s probably why I’m seeing the delays. Thanks so much for the response!
