### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by houdini479** [SpikeApp/Spike#29]
Not sure if this is where you want bug reports - let me know if there's somewhere else.

1.  updated to the 2.0.0 version
2.  Set spike to "follower" and entered the nightscout URL and API secret
3.  changed settingst o 12 hour clock and mmol/l 
4.  clicked back to get to main screen.
5.  App closed and cant seem to relaunch it.  Everytime I open the app not is briefly shows the main screen (and current nightscout data) than crashes.  Have tried force closing and restarting the phone - same issue.

device: iphone x.  

Cheers

**Comment by miguelkennedy** [comment]
This is fixed in version 2.0.1 that should be out tomorrow.

In the meantime, you can do this workaround:

1) Downgrade to 1.1.5 in TestFlight
2) Open 1.1.5 go to settings, share and enable Healthkit... Give permissions for blood glucose...
3) Close Spike from the app switcher
4) Go to the Health app, sources, Spike and disable permissions for glucose (this is optional and you should only do it if you don't want Spike to write glucose to HealthKit)
5) Upgrade to 2.0.0 and all should be fine now.
